### ISSUE TITLE
Create placeholder "Topic Landing Page"

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#16]
To massively increase SEO we should make landing pages for popular topics:

OpenAPI
REST
HTTP/2

These will be editorially written overviews with links to articles, tools, probably chuck a book link on there for good measure.

**Comment by TemitopeAsama** [comment]
> To massively increase SEO we should make landing pages for popular topics:
> 
> OpenAPI REST HTTP/2
> 
> These will be editorially written overviews with links to articles, tools, probably chuck a book link on there for good measure.

I can take this on. Are there designs for the landing pages or websites to take inspiration from?

**Comment by mbifulco** [comment]
Hey there @TemitopeAsama - we actually just launched a new site this week. Topic landing pages are a matter of configuration at this point, thankfully. Appreciate you reaching out - we'd love to have you contribute an article if there's anything API-related you're interested in writing about! Feel free to open another issue if you'd like to discuss.
