### ISSUE TITLE
Fix OG Meta Images

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#239]
<img width="786" alt="Screen Shot 2019-09-13 at 15 40 28" src="https://user-images.githubusercontent.com/67381/64927864-4ad9a580-d7de-11e9-9bd7-d2ee76f66121.png">
<img width="696" alt="Screen Shot 2019-09-13 at 15 40 31" src="https://user-images.githubusercontent.com/67381/64927865-4ad9a580-d7de-11e9-939a-a22744178171.png">

**Comment by mbifulco** [comment]
This is working for blog posts, but not books. test here: https://cards-dev.twitter.com/validator

![image](https://user-images.githubusercontent.com/1844496/147699059-b50ac3de-a81e-4eeb-a90a-57bbf9fd8c59.png)

**Comment by mbifulco** [comment]
To do:

- [ ] books pages
- [ ] home page
- [ ] global fallback to APIs You Won't Hate logo

**Comment by mbifulco** [comment]
fixed in #574
