### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#293]
We need one! Any ideas on where we can get a starter? It's not something I've done before.

**Comment by mbifulco** [comment]
This looks like a great resource -> https://www.contributor-covenant.org/

**Comment by matthewtrask** [comment]
That one is good. I've also used the one from Stumptown Syndicate that my google is failing me on right now for Southeast PHP. Im open to either. We just need to make sure we have a good enforcement platform.

**Comment by mbifulco** [comment]
Yeah, tell me more about that - what have you seen for enforcement, etc in the past?

**Comment by philsturgeon** [comment]
Yeah we need a way to submit things and we’ll look into it and kick people out without warning if they are being jerks. If it’s a minor dispute we can warn. 

--
Phil Sturgeon
@philsturgeon

**Comment by mbifulco** [comment]
Can we make an email address/alias for this? The Contributor Covenant above has a big ol' `INSERT ADDRESS HERE` spot for contact

**Comment by mbifulco** [comment]
@matthewtrask I found the one you were talking about - http://citizencodeofconduct.org/

**Comment by philsturgeon** [comment]
We only have phil@apisyouwonthate.com and despite that not being ideal I’m not paying for proper email hosting right now. 

--
Phil Sturgeon
@philsturgeon

**Comment by mbifulco** [comment]
Is that a google account? We could set up the code of conduct page to point to phil+coc@apisyouwonthate.com for now - that should make its way to the same address, and be easily filterable.
