### ISSUE TITLE
Jobs Board

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#31]
We should help people find jobs who want them, and vice versa. Should cut down on any spam in Slack and could be a bit of a fund raiser for other projects.

**Comment by mbifulco** [comment]
This is a great idea.  I feel like a regular newsletter would be a good complement to this.  We could send out a weekly dispatch of articles we've posted, and content/tools/whatever we've found elsewhere, with a list of open jobs at the bottom.

**Comment by philsturgeon** [comment]
Had this bookmark floating around, no idea if its any good. https://jobboardfire.com/?ref=betalist

**Comment by philsturgeon** [comment]
@matthewtrask how's this coming along? LOTS of people need jobs right now and we should help out.

**Comment by philsturgeon** [comment]
Done! Awesome work everyone. https://apisyouwonthate.com/jobs
