### ISSUE TITLE
Build APIs 2 Book Page

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#32]
New book needs new page.

**Comment by TemitopeAsama** [comment]
Kindly let me know and I'll get on it asap!

**Comment by philsturgeon** [comment]
Thank you, but this one isn’t needed as the book never got complete and I’m gonna finish up Surviving Other Peoples APIs first. https://apisyouwonthate.com/books/surviving-other-peoples-apis/
