### ISSUE TITLE
Authors Page

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#33]
Basic user profiles with a bio in the authors yaml file, subtle `@username` and `website.com`  and a shiny "Consulting" button which takes the clicker to whatever URL this person uses for consulting. I for example use https://calendly.com/philsturgeon others use clarity.fm or whatever.

**Comment by mbifulco** [comment]
Working on this in `feature/authors`.  Should this show _all_ authors of blog posts?

**Comment by philsturgeon** [comment]
I was thinking we could have some sort of distinction between "Contributing Authors" and "Staff Authors" or some other thing.

**Comment by mbifulco** [comment]
Working on the `/authors` landing page: 
![image](https://user-images.githubusercontent.com/1844496/66273574-2011c880-e843-11e9-86f1-a9f0d20ec281.png)

**Comment by mbifulco** [comment]
Anything missing from that view? I need to get together a bio / photo for @matthewtrask still.

I think I'll likely order the sections by number of articles contributed - that seem fair?
