### ISSUE TITLE
Text has big spaces around " on the blog

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#34]
<img width="734" alt="Screen Shot 2019-05-14 at 21 07 44" src="https://user-images.githubusercontent.com/67381/57726088-f509bb00-768e-11e9-9a24-fb5c849d4026.png">

**Comment by mbifulco** [comment]
@philsturgeon can you point me to a page that's showing this behavior?

**Comment by philsturgeon** [comment]
It was removed in https://github.com/apisyouwonthate/apisyouwonthate.com/pull/38 but if you look art the old commit or git reset back in time you should see the problem.

**Comment by philsturgeon** [comment]
It's also on paradigm picker  https://www.apisyouwonthate.com/blog/picking-the-right-api-paradigm
