### ISSUE TITLE
"About The Book" description the same on both books

### ISSUE THREAD

**Issue by ChrisDBrown** [apisyouwonthate/apisyouwonthate.com#37]
Sorry if this is a known issue - figured it was better to raise here than over Twitter etc. Currently both books have the "About The Book" content for Surviving Other People's APIs, making the content on the other book page a bit confusing.

https://github.com/apisyouwonthate/apisyouwonthate.com/blob/master/src/content/books/00-surviving-other-peoples-apis.mdx#L14:L18

https://github.com/apisyouwonthate/apisyouwonthate.com/blob/master/src/content/books/01-build-apis-you-wont-hate.mdx#L38:L42

**Comment by mbifulco** [comment]
🤦‍♂️ good catch!
