### ISSUE TITLE
Fix display logic for article layout on author pages 

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#375]
Related to #372  - when authors have a number of articles which is not-divisible-by-3, they display poorly:

![image](https://user-images.githubusercontent.com/1844496/67100897-8aedc880-f18e-11e9-999c-39105deaa7b7.png)

# Expected fix:
- article layout should left-align

**Comment by philsturgeon** [comment]
@mbifulco did this get sorted out?
