### ISSUE TITLE
Blog post cover image display is funky

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#405]
Opening this to track discussion around fixing the cover image on [blog post pages](https://apisyouwonthate.com/blog/openapi-callbacks-and-webhooks).

# The problem
The way the site is set up now, cover images are being partly obscured, which makes them unhelpful in many situations.  The cover image is set to have a max height of 60% of the browser's view height.

**current state**
![image](https://user-images.githubusercontent.com/1844496/67771505-cc079780-fa2e-11e9-8e13-d8984bada8ac.png)

## Option 1
Set the cover image to `center center` - some may get cut off still depending on the aspect ratio of the browser, but the center (and hopefully focal point) of the image will be shown:
![image](https://user-images.githubusercontent.com/1844496/67771634-08d38e80-fa2f-11e9-86b7-eb638d0b72cc.png)

# Option 2
Ditch the full-screen-width treatment, and display the image the same width as the article column, without limiting its height:

![image](https://user-images.githubusercontent.com/1844496/67784317-f9117580-fa41-11e9-88f7-50400476cfb7.png)

# Option 3
stick to full width and full height, which will completely hide article content for common desktop browser sizes:

![image](https://user-images.githubusercontent.com/1844496/67784430-29591400-fa42-11e9-8b32-a80785e48229.png)

**Comment by philsturgeon** [comment]
1! I will be cropping things wherever possible but center is better than top :)
