### ISSUE TITLE
Set up Open Graph Share images for twitter

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#48]
Open Graph sharing isn't working for twitter from the blog.  Blog cover images should show up as hero images on tweets about articles.

**Comment by philsturgeon** [comment]
I had a go at this but got lost in the SEO.js

Seems like my bike blog has this covered fairly simply, could we delete some code and shove in a thing like this? https://github.com/philsturgeon/phil.bike/blob/7da02eb30804fd2473cc7776757b0929e994a5bb/src/templates/post.tsx

**Comment by mbifulco** [comment]
Closed via #51
