### ISSUE TITLE
Mobile responsive presentation issues

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#49]
There's a good handful of responsive design issues to handle for mobile viewports:

https://twitter.com/juokaz/status/1130484949851791363
![image](https://user-images.githubusercontent.com/1844496/58103033-4a265f00-7bb0-11e9-95b2-f4203b9638a4.png)

https://twitter.com/shadowhand/status/1130503308530003968
![image](https://user-images.githubusercontent.com/1844496/58103069-56122100-7bb0-11e9-91d8-bbd6aaa0d171.png)

**Comment by philsturgeon** [comment]
Testing article has some troubles with the gif falling off the side. 
![98174665-F709-423F-8943-427FE81A5C61](https://user-images.githubusercontent.com/67381/59174588-2bcdd680-8b52-11e9-8b5c-cb12c1e8995e.png)
