### ISSUE TITLE
Import a few more jobs

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#524]
If these look any good, lets manually shove them in and I'll expand the scraper in the future to pull things in from multiple sources. 

- [x] https://remotive.io/remote-jobs/software-dev/senior-backend-engineer-data-and-platform-216018
- [x] https://remotive.io/remote-jobs/software-dev/sr-fullstack-developer-react-java-216126
- [ ] https://remoteok.io/remote-jobs/84776-remote-java-api-developer-pricesenz
- [ ] https://remotive.io/remote-jobs/software-dev/lead-api-automated-software-development-engineer-in-test-sdet-214559
- [ ] https://stackoverflow.com/jobs/384774/lead-api-automated-software-development-railroad19
- [ ] https://remotive.io/remote-jobs/software-dev/senior-backend-engineer-data-and-platform-216018

**Comment by matthewtrask** [comment]
word! Ill take a look at these today :)

**Comment by matthewtrask** [comment]
Ill look at expanding the scraper too just so Im familiar with it.

**Comment by mbifulco** [comment]
This process is now automated - we're importing _heaps_ of jobs from Remotive whenever the site is built. We can set up a nightly build to refresh these jobs, to keep them fresh.
