### ISSUE TITLE
Footer links become invisible on hover

### ISSUE THREAD

**Issue by 99littlebugs** [apisyouwonthate/apisyouwonthate.com#538]
![Screen+Recording+2021-05-04+at+09 46 45 79+PM](https://user-images.githubusercontent.com/7087640/117089051-5ca8ed00-ad22-11eb-986d-00a839a349fb.gif)

**Comment by mbifulco** [comment]
Good catch - thank you @99littlebugs

**Comment by mbifulco** [comment]
Closed by #538 - thank you both!
