### ISSUE TITLE
Fix display overflow on blog pages from image section

### ISSUE THREAD

**Issue by inverse** [apisyouwonthate/apisyouwonthate.com#547]
![image](https://user-images.githubusercontent.com/713525/138433280-fedd3b03-6fc7-4f21-8578-e351d528ca29.png)

Example page: https://apisyouwonthate.com/blog/theres-no-reason-to-write-openapi-by-hand

**Comment by inverse** [comment]
Was the issue resolved? I'm still seeing it.

**Comment by mbifulco** [comment]
> Was the issue resolved? I'm still seeing it.

Hey there @inverse ! I'm working on a redesign of the site which was just closed in #554, and should be live in the next few days. This bug is one of the many things addressed in that PR. Feel free to re-open this, and I'll tag you to check it out once we've made the new site live.

**Comment by inverse** [comment]
Thanks for explaining - wasn't aware that was going on! looking forward to seeing the new look :)
