### ISSUE TITLE
Add shopify buy button functionality to books pages

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#557]
Shopify buy button is broken for compilations on M1 Macs currently.  It should be patched soon to work via https://github.com/Shopify/buy-button-js/pull/792

For now, I'm going to import this library from a CDN - http://shopify.github.io/buy-button-js/

**Comment by mbifulco** [comment]
_actually_ for now I generated a checkout link from Shopify - not as tidy as the buy button, but it works.  I'll revisit this when/if the linked buy button PR gets merged

**Comment by philsturgeon** [comment]
Another option we talked about was Stripe which I think we can use directly to cut out Shopify, as we _only_ use the checkout and we no longer accept bitcoin or any of that planet burning nonsense. If we chose to sell physical books again I'm sure we can hook that up without needing to use Shopify+Sendowl, that seems expensive and we could slap in some magic automation glue ourselves somewhere.
