### ISSUE TITLE
Replace embedded mailjet newsletter form with an API call and a fresh UI

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#569]
Right now we have a mailjet form that works via embedded iframe that attempts to resize itself, and it doesn't always work well:

![image](https://user-images.githubusercontent.com/1844496/147827564-1376c890-3b80-40d0-aa9d-5da99480f58a.png)

goal: replace this iframe in [NewsletterForm.js](https://github.com/apisyouwonthate/apisyouwonthate.com/blob/main/src/components/NewsletterForm/NewsletterForm.js) with some nice UI that calls the [Mailjet Contact API](https://dev.mailjet.com/email/guides/contact-management/#single-contact-management) directly, likely via an API route in this project (`/api/newsletter` etc)

**Comment by philsturgeon** [comment]
Maybe https://formspree.io/ but that's just more embedded JS to worry about. 

Lighthouse and EcoPing are both complaining about the mailjet JS so if we can just do this with an API call that'd be lovely.

<img width="660" alt="Screen Shot 2022-01-03 at 2 34 37 PM" src="https://user-images.githubusercontent.com/67381/147943360-eb115799-3e96-45e5-a3c3-4b6559d82c9d.png">

**Comment by mbifulco** [comment]
Should be able to, yeah. I'll work on this next.On Jan 3, 2022 9:39 AM, Phil Sturgeon ***@***.***> wrote:
Maybe https://formspree.io/ but that's just more embedded JS to worry about.
Lighthouse and EcoPing are both complaining about the mailjet JS so if we can just do this with an API call that'd be lovely.
