### ISSUE TITLE
Automatically resize cover images to be thumbnails on home/blog page

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#576]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/67381/147944830-c2373ed3-0b2c-417d-8932-31a90125890d.png">

**Comment by philsturgeon** [comment]
Featured blog post, posts, and even book covers should all be auto-resized with next/image to avoid overly large images being squished in. 

I tried and had some trouble, as I could not figure out a combination of width/height/layout that would work in all situations. Perhaps if they had a CSS wrapper they could be filled to that size? Anyhow, im not the frontend person, so somebody else can figure that out. :D

**Comment by philsturgeon** [comment]
We're up to 90 on lighthouse but this issue would solve the remaining issues. 

<img width="628" alt="image" src="https://user-images.githubusercontent.com/67381/147972128-fedc52d1-7347-48fd-8207-3725e7db1adf.png">

All of these would be fixed if feature/blog thumbs/books were using next/image.

**Comment by mbifulco** [comment]
fixed in #578
