### ISSUE TITLE
Add RSS autodiscovery metadata

### ISSUE THREAD

**Issue by jamietanna** [apisyouwonthate/apisyouwonthate.com#595]
To allow folks to point a feed reader to the site, we need to add i.e.:

```html
<link rel=alternate type=application/rss+xml href=/feed.xml title="Jamie Tanna | Software Engineer">
```

To the `<head>`.

**Comment by mbifulco** [comment]
Ah good catch - TIL this was a thing! Pushing a fix momentarily. 

Anything else we can do to make RSS better for the site?

**Comment by jamietanna** [comment]
Sorry @mbifulco I missed this - I'd say if possible having the podcast as its own feed, and with landing pages per episode that can be linked out to, as i.e. if I want to share it with others I need to either link the MP3 or use `player.fm` or similar sites
