### ISSUE TITLE
Footer tidy up

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#601]
The footer has lots of useful stuff but I think we could tidy it up a little. Here's an absolute gem from laracasts.com

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67381/154666425-b5486d4d-ee2b-4f14-989d-784a1f78333a.png">

Let's see if we can get it more balanced for vrious screen sizes like this, because here's what im seeing.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67381/154666618-0fb22b9c-af46-493b-be40-4f8e319ed919.png">

**Comment by mbifulco** [comment]
Love this - Laracasts' footer looks great! I'll take a swing at this soon.

**Comment by TemitopeAsama** [comment]
Nicee. I'd love to take this on.

**Comment by philsturgeon** [comment]
@TemitopeAsama would you be up for helping us out? Can throw some trees/money if you get this PR in.

**Comment by TemitopeAsama** [comment]
Sure thing! Will get to it tomorrow!

Thank you for the opportunity!

**Comment by TemitopeAsama** [comment]
Essentially, we're looking at a more robust and responsive footer, i.e. more information and improved layout for various screen sizes, yes?

@philsturgeon

**Comment by mbifulco** [comment]
That's right - something that's a little more modern looking, and works on mobile and desktop viewports. Feel free to drop any questions you've got here. Thanks @TemitopeAsama!

**Comment by TemitopeAsama** [comment]
Hi @mbifulco, I'm looking at a short summary of what APIs You Won't Hate is all about. From the site, there's very little information as to what it's about, so I'm looking to do something quite similar to LaraCast's simple footer bio.

If you have any bio ideas, I'd appreciate them. Also, kindly let me know if you want me to use my discretion.
Thank you!

![](https://user-images.githubusercontent.com/67381/154666425-b5486d4d-ee2b-4f14-989d-784a1f78333a.png)

**Comment by matthewtrask** [comment]
a starting point would be "APIs You Wont Hate is the recommended manual for building well designed and well crafted APIs. Join us, read our blog posts, search our community of knowledge and put it to good use building robust APIs" or something similar.

**Comment by TemitopeAsama** [comment]
Nice! Thank you, Phil!

**Comment by TemitopeAsama** [comment]
Nice. Note taken. Thank you!

**Comment by TemitopeAsama** [comment]
Sure thing, Will! I'll get to it tomorrow. Thank you for reaching out!

**Comment by philsturgeon** [comment]
@TemitopeAsama hey did you get a chance to tackle this at all? I'm about to start putting a lot more energy into this website so would love to get it looking A++.

**Comment by TemitopeAsama** [comment]
Hello Phil. No I haven't yet. I am currently recovering from surgery and
have not had the chance to tackle it yet. However, I will get to it by
weekend and give you updates in my progress.

Happy New Year!
