### ISSUE TITLE
what kind of content makes sense to supplement documentation?

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#609]
Placeholder issue for a guest post from  [Karl Hughes](https://twitter.com/karllhughes)

To Do:
- [x] Karl to draft post
- [ ] team reviews post
- [ ] team approves post
- [ ] create Author page for Karl ([mine, for reference](https://github.com/apisyouwonthate/apisyouwonthate.com/blob/main/src/content/authors/mike-bifulco.mdx))
- [ ] PR for new post
- [ ] proofread
- [ ] go-live
- [ ] tweet!

**Comment by karllhughes** [comment]
@mbifulco I've got a first draft here: https://docs.google.com/document/d/1u76sSYOArYpa3kMe5E8waAzbKC-_DxuquT1lMDLgUgM/edit?usp=sharing

It's in Markdown, so if you prefer, I can go ahead and make a PR, but happy to work off the Google doc for the first round.

Looking forward to hearing what you think, feedback is always appreciated! 👍

**Comment by mbifulco** [comment]
Thanks @karllhughes - let's keep it in the Google Doc for now, I'll review it today.

**Comment by mbifulco** [comment]
@karllhughes I really only had one small edit to suggest for your post - take a look when you get a chance. I'm happy to take it from there and drop it into a PR, or you're welcome to tackle that if you'd prefer. Thanks so much!

**Comment by karllhughes** [comment]
@mbifulco agreed, I just reworked that sentence so I think it's more clear, but LMK what you think.

If that looks good, I'll make the PR this week. Thanks!

**Comment by karllhughes** [comment]
@mbifulco I went ahead and made a PR. Just let me know what else you need from me, thanks!
