### ISSUE TITLE
Missing link on OpenAPI 3.1 tools update

### ISSUE THREAD

**Issue by jamietanna** [apisyouwonthate/apisyouwonthate.com#614]
There's a link out to https://hackmd.io/Y9WDJt9KRYaPPNBgZpajsQ which appears to be a draft of the article, instead of maybe a link out to OpenAPI.tools?

**Comment by philsturgeon** [comment]
where?

**Comment by jamietanna** [comment]
Sorry, was reporting quickly on mobile:

> existing [JSON Schema tooling](https://hackmd.io/Y9WDJt9KRYaPPNBgZpajsQ) instead

**Comment by philsturgeon** [comment]
OH over here: https://www.openapis.org/blog/2022/05/11/openapi-v3-1-resources-for-tooling-developers 

Totally different website I was very confused. Thank you :D
