### ISSUE TITLE
Add a home/feature for the podcast on apisyouwonthate.com

### ISSUE THREAD

**Issue by mbifulco** [apisyouwonthate/apisyouwonthate.com#70]
Where should the podcast live on the website? 
Should we have a blog post entry for each episode?

**Comment by philsturgeon** [comment]
For now we can just link in the header to our anchor.fm profile but this should in the future get its own feed page. I'd rather keep it out of blog, or at least if it uses the same blog logic we could make a different page with its own layout to keep the content separate.

**Comment by philsturgeon** [comment]
@mbifulco can you take a stab at this? We gotta get the podcast up.

**Comment by mbifulco** [comment]
@philsturgeon working on this now 👍
