### ISSUE TITLE
Consistent avatar and cover photo

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#79]
We need to get something for an avatar and cover photo.

Cover Photo:

- Twitter
- Github
- philsturgeon.uk background instead of just that purple

Avatar:

- Twitter
- GitHub
- Podcast (anchor.fm)

I think the avatar can be the cover but we gotta get the typogrophy on there. This is not ok.

![image](https://user-images.githubusercontent.com/67381/59412772-76538b00-8dbe-11e9-8ef3-2b58a8e54fc3.png)

@mbifulco I have the source files for the cover so we can hopefully do something good with it?

**Comment by mbifulco** [comment]
Link me to those source files when you get a chance @philsturgeon

**Comment by philsturgeon** [comment]
Slacked em! 

--
Phil Sturgeon
@philsturgeon

**Comment by mbifulco** [comment]
Alright peeps - pick a favorite, and I'll sure it up and get versions out for all the sizes we need

![image](https://user-images.githubusercontent.com/1844496/60338585-5b634800-9974-11e9-976f-bca7e8f921cf.png)

**Comment by mbifulco** [comment]
Bleh, alright, I take it all back.  I'm leaning towards going with this.  The `(the podcast)` bit will obviously be omitted on the website, etc

 Any tweaks you'd like me to make before I have a go at other sizes?

![podcover](https://user-images.githubusercontent.com/1844496/60341391-50141a80-997c-11e9-9b77-6f5bafeb7f5b.png)

**Comment by philsturgeon** [comment]
I like 4, it’s a good size and the foot is kicking hate which is cool. 2 has potential if the foot was in the right place and it was making use of space a bit more. Some of the avatars can get a bit small so the smaller the text gets the harder it’ll be to read or even recognise next to a tweet for example. I know “make the logo bigger” is a meme but... 🤷🏻‍♂️



--
Phil Sturgeon
@philsturgeon

**Comment by mbifulco** [comment]
I dig that.  I'll mock up some smaller sizes with copy 4 as a starting point.

**Comment by mbifulco** [comment]
Alright guys, trying to get together a list of places to get the logo treatment uploaded to:

- [ ] twitter - @philsturgeon has access to this
- [ ] patreon - I think @matthewtrask owns this
- [ ] the website - I'll put this in its own PR 
- [ ] anchor.fm (podcast)
- anything else?

**Comment by philsturgeon** [comment]
Github 

--
Phil Sturgeon
@philsturgeon

**Comment by mbifulco** [comment]
@philsturgeon I don't have access to change the image on GitHub - can you swap it for this?
![apis-you-wont-hate-square](https://user-images.githubusercontent.com/1844496/63344185-d108e600-c31d-11e9-85f8-c603c2d08443.png)

**Comment by matthewtrask** [comment]
I don't think we really went ahead with Patreon, so I think I can just delete it. Unless we want to give it another try?

**Comment by philsturgeon** [comment]
Nah no need for patreon 


On August 20, 2019 at 17:50:02, Matt Trask (notifications@github.com) wrote:

I don't think we really went ahead with Patreon, so I think I can just delete it. Unless we want to give it another try?

**Comment by philsturgeon** [comment]
Amazing, you did it! :D
