### ISSUE TITLE
Podcast Improvements

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/apisyouwonthate.com#94]
Let's get icons up on the Podcast page for helping folks find our RSS, iTunes and other things. If we reuse the icons from https://anchor.fm/apisyouwonthate it should be easy to add new ones in the future.  Just plain old HTML is fine lets not get fancy.

Also, we still linking to anchor https://www.apisyouwonthate.com/podcast/ and we could make the footnotes be actual markdown instead of kinda plain text.

**Comment by philsturgeon** [comment]
@mbifulco repurposed this old issue.

**Comment by mbifulco** [comment]
We should also link to the ama page from the pocast page, per https://twitter.com/freyfogle/status/1222858000001572864

(Thanks for the suggestion!)
